# Generated by Django 4.2.2 on 2023-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_orderposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produt',
            new_name='Product',
        ),
    ]
