# Generated by Django 4.2.2 on 2023-07-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_produt_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
